### ISSUE TITLE
DontShipItWithYourGame folders included in upload? Perhaps causing commit failure

### ISSUE THREAD

**Issue by ztffn** [tomicz/unity-steam-macos-deployer#1]
Hi, this will be a great tool, But, I have yet to find success with it. 

The error (ERROR! Failed to commit build for AppID redacted : Failure) seems to be related to it trying to upload the "BackUpThisFolder_ButDontShipItWithYourGame" folder that unity creates post-build. 

A couple of other remarks, would be nice to run the console commands, without making a fresh build each time. A lot of my error tracking has been with other steamworks issues, like trying to upload to a depot before having published it. Making a build for each attempt, adds to the frustration.

Might also want to add a line about the user having to chmod steamcmd.sh before running it.

**Comment by tomicz** [comment]
It's not because of the folder "BackUpThisFolder_ButDontShipItWithYourGame", but my theory is that it is because I didn't select the right branch before uploading. I still need to investigate it to confirm it. Though it does not prevent you from uploading builds, your build is available under builds on your Steam dashboard page. And thanks for letting me know about DoNotShip folder, I will auto-remove it on the first build in future commits. 

Also, feel free to contribute, it's an open-source project. I would love to learn how other people make builds. 

`A couple of other remarks, would be nice to run the console commands, without making a fresh build each time. A lot of my error tracking has been with other Steamworks issues, like trying to upload to a depot before having published it. Making a build for each attempt adds to the frustration.`

I don't understand this part. Could you elaborate more? Builds are not published immediately, you have to publish them manually in your builds dashboard and publish pages. But feel free to elaborate more, I would love to learn how people use this tool so that I can improve it.

**Comment by tomicz** [comment]
> Hi, this will be a great tool, But, I have yet to find success with it.
> 
> The error (ERROR! Failed to commit build for AppID redacted : Failure) seems to be related to it trying to upload the "BackUpThisFolder_ButDontShipItWithYourGame" folder that unity creates post-build.
> 
> A couple of other remarks, would be nice to run the console commands, without making a fresh build each time. A lot of my error tracking has been with other steamworks issues, like trying to upload to a depot before having published it. Making a build for each attempt, adds to the frustration.
> 
> Might also want to add a line about the user having to chmod steamcmd.sh before running it.

Upon investigation, I discovered that DoNotShip folder is only generated when compiling with IL2CPP scripting backend. I am going to give an option to delete DoNotShip folder. Devs might need that folder so I want to make it optional. 

Also I am going to give option to generate a build without uploading to Steam. There are going to be buttons Generate Build and Upload.

See documentation [IL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html)
